
platform :ios, '7.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'


target 'ECSDK-alipay' do
    pod 'RedpacketAliAuthLib'
end


target 'ECSDK-JDpay' do
    pod 'RedpacketLib'
end
