
platform :ios, '7.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'ECSDK-alpayOpenUI' do
    pod 'RedPacketAliAuthUI', :path => 'cocoapods-redpacket-ui-2.0.0'
end


target 'ECSDK-JDpay' do
    pod 'RedpacketLib'
end
